### ISSUE TITLE
Install fails on a fresh machine because of self install

### ISSUE THREAD

**Issue by jdfreder** [jovyan/jupyter-devinstall#29]
I have trouble installing on fresh machine where I've installed jupyter-devinstall globally using `npm install -g jupyter-devinstall`.  Running `jupyter-devinstall` then, by default, tries to install itself.  This leads to conflicts on install.  Typically I just use the `-N` flag to skip npm installs (which skips this), but soon we will have other npm project which I wont want to skip.  I propose removing jupyter-devinstall from the list of projects cloned/installed by jupyter-devinstall.

cc @SylvainCorlay

**Comment by SylvainCorlay** [comment]
ok.
