### ISSUE TITLE
Provide a command to 'reinstall' on top of a new python

### ISSUE THREAD

**Issue by fperez** [jovyan/jupyter-devinstall#4]
Since, in addition to cloning lots of repos, this also does a lot of local setups, it would be very useful to be able to rerun just that last step separately.  

For example, when you install a new python (say 3.5), you'll need to rerun all those again, since they go to `~/.local/lib/python3.X/site-packages/`. 

But you don't want to redo all the cloning and other steps.  

Maybe it's already safe to re-run in place multiple times, but if so, the docs/readme should indicate that usage pattern explicitly at least...

**Comment by jdfreder** [comment]
#6 doesn't really solve this, but it's a step in the right direction
